--- Makefile
+++ Makefile
@@ -1,7 +1,7 @@
 ##################################################################################
 # WHATEVER YOU DO, PLEASE DO IT TO Makefile.config AND LEAVE THIS MAKEFILE ALONE #
 ##################################################################################
-include Makefile.config
+# include Makefile.config
 
 
 #------------------------------------------------------------------#
@@ -25,7 +25,7 @@
 AHF:	FORCE dirs
 	cd src;\
 	${MAKE} AHF;\
-	mv -f AHF ../bin/AHF-v1.0-094
+	mv -f AHF ../bin/$(AHF_BIN)
 
 
 # everything in convert/
