# General

PROTECT_FROZEN_FIRE

OPENMP={{ OPENMP }}

BOX_PERIODIC
PMGRID=1024
PM_PLACEHIGHRESREGION=1+2+16
PM_HIRES_REGION_CLIPPING=2000
MULTIPLEDOMAINS=32

OUTPUT_POSITIONS_IN_DOUBLE
OUTPUT_POTENTIAL
IO_COMPRESS_HDF5
STOP_WHEN_BELOW_MINTIMESTEP

# Baryon

ADAPTIVE_GRAVSOFT_FORGAS

HYDRO_MESHLESS_FINITE_MASS

COOLING
COOL_LOW_TEMPERATURES
COOL_METAL_LINES_BY_SPECIES
METALS
TURB_DIFF_METALS

GALSF
GALSF_SFR_MOLECULAR_CRITERION
GALSF_SFR_VIRIAL_SF_CRITERION=0
FIRE_PHYSICS_DEFAULTS

ALLOW_IMBALANCED_GASPARTICLELOAD
