general:
    box_length: 60  # in comoving Mpc
    z_start: 50
    z_end: 2
    baryon: true
    zoom: true
data:
    output_times: config/output_times.txt
    zoom_region: config/zoom_region/z2h350.txt
cosmology:
    h: 0.703
    Omega_m: 0.276
    Omega_L: 0.724
    Omega_b: 0.045
    sigma_8: 0.811
    n_s: 0.961
music:
    source: https://bitbucket.org/ohahn/music
    commit: 12e7b54e7512e7ca5ed19875b643137c59379a20
    levelmin: 8
    levelmin_TF: 10
    levelmax: 12
    padding: 6
    overlap: 4
    job:
        omp_threads: 28
        time: '01:00:00'
gizmo:
    source: ssh://hg@bitbucket.org/phopkins/gizmo
    commit: 4fd12fbd8bf81edaa9d710b728ebbefa1e3e51b1
    # Numerics
    softening:  # all in physical pc
        dm_lr: 320
        dm: 80
        star: 8
        gas: 1
        z: 9  # the redshift at which the softening switches to physical
    CritPhysDensity: 1000  # critical physical density for star formation (cm^(-3))
    # Runtime
    NumFilesWrittenInParallel: 8
    TimeLimitCPU: 202000  # 2 days
    MaxMemSize: 4000  # < 128 / mpi_tasks * 1000 == 4571
    PartAllocFactor: 3
    TreeDomainUpdateFrequency: 0.005
    job:
        nodes: 4
        mpi_tasks: 28  # per node
        omp_threads: 1  # per task
        time: '48:00:00'
