JOB_NAME = h01-dm
CONFIG_ZOOM_REGION = h01-box-rad4.txt
CONFIG_MUSIC_CONF = dmo-ref13.conf
CONFIG_GIZMO_CONFIG = dmo.sh
CONFIG_GIZMO_PARAMS = dmo.txt

include ../template/Makefile
include ../template/Makefile.dmo
