halo_name = "h11"
zoom_region = "h11-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_022/snapshot_022"
TimeLimitCPU = 202000
MaxMemSize = 8000
PartAllocFactor = 2
BufferSize = 160

[job]

[job.ic]
site = "bridges"
queue = "RM-small"
omp = 28
hour = 8

[job.run]
site = "bridges"
queue = "RM"
nodes = 64
mpi = 14
omp = 2
hour = 48
