JOB_NAME = $(HALO)-$(SIM_TYPE)-$(REF_LVL)

# GIZMO version: FIRE_FrozenBranch at 2018-06-17
GIZMO_REPO = ssh://hg@bitbucket.org/phopkins/gizmo
GIZMO_COMMIT = 76dbfab6c0fbef056b713410e5eb73f8c1b00205

ifeq ($(SIM_TYPE),hyd)
HAS_BARYONS = yes
else
HAS_BARYONS = no
endif

ifeq ($(REF_LVL),13)
SNAP_FILES = 4
else
SNAP_FILES = 1
endif

# dmo-12 on TSCC
ifeq ($(SIM_TYPE)-$(REF_LVL),dmo-12)
ZOOM_REGION = $(HALO)-box-rad4.txt
JOB_IC_SCRIPT = ic.tscc.sh
JOB_IC_SUBMIT = qsub -q condo -N
JOB_IC_OMP = 32
JOB_RUN_SCRIPT = run.tscc.sh
JOB_RUN_SUBMIT = qsub -l nodes=4:ppn=16:ib -N
JOB_RUN_OMP = 1
JOB_RUN_MPI = 16
JOB_RUN_TIME = 33000
JOB_RUN_MEM = 7500
JOB_RUN_BUF = 200
endif

# hyd-13 on Bridges
ifeq ($(SIM_TYPE)-$(REF_LVL),hyd-13)
ZOOM_REGION = $(HALO)-dmo-12-rad4.txt
JOB_IC_SCRIPT = ic.bridges.sh
JOB_IC_SUBMIT = sbatch -J
JOB_IC_OMP = 28
JOB_RUN_SCRIPT = run.bridges.sh
JOB_RUN_SUBMIT = sbatch --nodes=32 -J
JOB_RUN_OMP = 2
JOB_RUN_MPI = 14
JOB_RUN_TIME = 202000
JOB_RUN_MEM = 8000
JOB_RUN_BUF = 200
endif
