JOB_NAME = $(HALO_LABEL)-dm
CONFIG_ZOOM_REGION = $(HALO_LABEL)-box-rad4.txt
CONFIG_MUSIC_CONF = dmo-ref13.conf
CONFIG_GIZMO_CONFIG = dmo.sh
CONFIG_GIZMO_PARAMS = dmo.txt

.PHONY: submit-run
files: job/run.sh
submit-run: job/run.sh
	cd job && sbatch -J $(JOB_NAME) run.sh
job/run.sh: ../template/job/run-dmo.sh | job
	cp -f $< $@
