package:
  name: ahf
  version: 1.0.094

source:
  url: http://popia.ft.uam.es/AHF/files/ahf-v1.0-094.tgz
  patches:
    - Makefile.patch

build:
  script_env:
   - LOCAL_CC
   - LOCAL_FC
   - LOCAL_OPT_OMP

test:
  commands:
    - which AHF
    - which AHF-dmo

about:
  home: http://popia.ft.uam.es/AHF/
