name: box_60_ref9_music  # box_{box_length}_ref{level}_{cosmology}
template: template
general:
    box_length: 60  # in comoving Mpc
    z_start: 50
    z_end: 2
    baryon: false
    zoom: false
data:
    output_times: data/output_times.txt
cosmology:
    h: 0.703
    Omega_m: 0.276
    Omega_L: 0.724
    Omega_b: 0.045
    sigma_8: 0.811
    n_s: 0.961
music:
    source: https://bitbucket.org/ohahn/music
    commit: 12e7b54e7512e7ca5ed19875b643137c59379a20
    levelmin: 9
    levelmin_TF: 9
    levelmax: 9
    padding: 0
    overlap: 4
    job:
        omp_threads: 28
        time: '00:15:00'
gizmo:
    source: https://bitbucket.org/phopkins/gizmo
    commit: 4fd12fbd8bf81edaa9d710b728ebbefa1e3e51b1
    # Numerics
    softening:  # all in physical pc
        dm_lr: 280
        dm: 80
        star: 8
        gas: 1
        z: 9  # the redshift at which the softening switches to physical
    # Runtime
    NumFilesWrittenInParallel: 8
    TimeLimitCPU: 200000  # 2 days
    MaxMemSize: 7000  # < 128 / mpi_tasks * 1000 == 9143
    PartAllocFactor: 3
    job:
        nodes: 4
        mpi_tasks: 14  # per node
        omp_threads: 2  # per task
        time: '48:00:00'
