#!/bin/bash
#SBATCH --job-name={{ name }}-music
#SBATCH --export=ALL
#SBATCH --partition=RM
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={{ music.job.omp_threads }}
#SBATCH --time={{ music.job.time }}
#SBATCH --output=job/music.%j.o
#SBATCH --error=job/music.%j.e
# This is adapted from the sample batch script for OpenMP job in
# https://www.psc.edu/bridges/user-guide/running-jobs

set -x
cd $REPO_ROOT/run/{{ name }}/ic

export OMP_NUM_THREADS=$SLURM_NTASKS
./music/MUSIC music.conf
