channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - nextflow
  - python=3
  - cython
  - matplotlib
  - numpy
  - pandas
  - scipy
  - yt
  - pip:
    - git+https://github.com/qobilidop/ahfio.git
