halo_name = "h00"
zoom_region = "h00-box-rad4"

[gizmo]
TimeLimitCPU = 200000
MaxMemSize = 7000
PartAllocFactor = 2
BufferSize = 140

[job]

[job.ic]
site = "stampede2"
queue = "skx-dev"
omp = 48
hour = 2

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 16
mpi = 24
omp = 2
hour = 48
