halo_name = "h10"
zoom_region = "h10-box-rad4"

[gizmo]
# InitCondFile = "output/snapdir_117/snapshot_117"
InitCondFile = "output/snapdir_119/snapshot_119"
TimeLimitCPU = 200000
MaxMemSize = 14000
PartAllocFactor = 3
BufferSize = 1000

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 128
mpi = 12
omp = 4
hour = 48
