halo_name = "h11"
zoom_region = "h11-box-rad4"

[gizmo]
# InitCondFile = "output/snapdir_087/snapshot_087"
InitCondFile = "output/snapdir_109/snapshot_109"
TimeLimitCPU = 200000
MaxMemSize = 14000
PartAllocFactor = 3
BufferSize = 1000

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 128
mpi = 12
omp = 4
hour = 48
