halo_name = "h11"
zoom_region = "h11-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_087/snapshot_087"
TimeLimitCPU = 200000
MaxMemSize = 7000
PartAllocFactor = 3
BufferSize = 210

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 64
mpi = 24
omp = 2
hour = 48
