halo_name = "h02"
zoom_region = "h02-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_040/snapshot_040"
TimeLimitCPU = 200000
MaxMemSize = 8000
PartAllocFactor = 2
BufferSize = 160

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "bridges"
queue = "RM"
nodes = 48
mpi = 14
omp = 2
hour = 48
