halo_name = "h00"
zoom_region = "h00-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_105/snapshot_105"
TimeLimitCPU = 200000
MaxMemSize = 7000
PartAllocFactor = 2
BufferSize = 140

[job]

[job.ic]
site = "bridges"
queue = "RM"
omp = 28
hour = 48

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 64
mpi = 24
omp = 2
hour = 48
