halo_name = "h00"
zoom_region = "h00-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_112/snapshot_112"
TimeLimitCPU = 200000
MaxMemSize = 7000
PartAllocFactor = 3
BufferSize = 140

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 64
mpi = 24
omp = 2
hour = 48
