halo_name = "h10"
zoom_region = "h10-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_118/snapshot_118"
TimeLimitCPU = 200000
MaxMemSize = 8000
PartAllocFactor = 2
BufferSize = 160

[job]

[job.ic]
site = "bridges"
queue = "RM-small"
omp = 28
hour = 8

[job.run]
site = "bridges"
queue = "RM"
nodes = 64
mpi = 14
omp = 2
hour = 48
