halo_name = "h10"
zoom_region = "h10-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_119/snapshot_119"
TimeLimitCPU = 200000
MaxMemSize = 7000
PartAllocFactor = 3
BufferSize = 210

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "stampede2"
queue = "skx-normal"
nodes = 96
mpi = 24
omp = 2
hour = 48
