halo_name = "h00"
zoom_region = "h00-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_114/snapshot_114"
TimeLimitCPU = 200000
MaxMemSize = 8000
PartAllocFactor = 3
BufferSize = 240

[job]

[job.ic]
site = "tscc"
queue = "condo"
omp = 16
hour = 8

[job.run]
site = "bridges"
queue = "RM"
nodes = 96
mpi = 14
omp = 2
hour = 48
