halo_name = "h03"
zoom_region = "h03-box-rad4"

[gizmo]
InitCondFile = "output/snapdir_048/snapshot_048"
TimeLimitCPU = 200000
MaxMemSize = 8000
PartAllocFactor = 2
BufferSize = 160

[job]

[job.ic]
site = "bridges"
queue = "RM"
omp = 28
hour = 48

[job.run]
site = "bridges"
queue = "RM"
nodes = 64
mpi = 14
omp = 2
hour = 48
