channels:
  - ./conda/channel
  - conda-forge
dependencies:
  # Locally built
  - ahf
  - fftw
  # General
  - hdf5=1.8.16  # Match the system version
  - jinja2
  - numpy
  - python=3
  - pyyaml
  - scipy
  - yt
