channels:
  - yt-project/label/dev
  - conda-forge
dependencies:
  - cython
  - h5py
  - numpy
  - pandas
  - pytables
  - python=3.6
  - yt
  - pip:
    - git+https://github.com/qobilidop/ahfriend
    - git+https://github.com/qobilidop/libdil
