HALO = h02
IC_TYPE = box
SIM_TYPE = hyd
REF_LVL = 13

include ../template/Makefile.config

# Generate IC on TSCC using larger memory node
JOB_IC_SCRIPT = ic.tscc.sh
JOB_IC_QUEUE = pdafm
JOB_IC_OMP = 16
JOB_IC_HOUR = 8

include ../template/Makefile
